spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: tdd-admin
    password: ""
    driverClassName: org.h2.Driver
  profiles:
    default: dev

security:
  oauth2:
    client:
      tmc:
        clientAuthenticationMethod: basic
        authorizedGrantType: authorization_code
        authorizationUri: http://localhost:8080/fake/authorize
        tokenUri: http://localhost:8080/fake/token
        userInfoUri: http://localhost:8080/fake/userinfo
        userNameAttributeName: username
        scopes: public
        clientName: TMC
        clientAlias: tmc
        redirectUri: http://localhost:8080/oauth2/authorize/code/tmc

tmc:
  sandboxUrl: http://localhost:8080
  notifyUrl: http://localhost:8080/submission-result

logging:
  level:
    ROOT: INFO
    pingis: DEBUG
