spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: tdd-admin
    password: ""
    driverClassName: org.h2.Driver
  profiles:
    default: dev

security:
  oauth2:
    client:
      tmc:
        clientAuthenticationMethod: basic
        authorizedGrantType: authorization_code
        authorizationUri: https://tmc.mooc.fi/oauth/authorize
        tokenUri: https://tmc.mooc.fi/oauth/token
        userInfoUri: https://tmc.mooc.fi/api/v8/users/current
        userNameAttributeName: username
        scopes: public
        clientName: TMC
        clientAlias: tmc
        redirectUri: http://localhost:8080/oauth2/authorize/code/tmc

tmc:
  sandboxUrl: http://localhost:3001
  notifyUrl: http://localhost:1337/submission-result

